# Generated by Django 4.0.1 on 2022-01-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
