# Generated by Django 4.0.1 on 2022-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание')),
                ('category', models.CharField(choices=[('other', 'разное'), ('clothes', 'одежда'), ('equipment', 'оборудование'), ('information', 'информативные')], max_length=100, verbose_name='категории')),
                ('balance', models.PositiveIntegerField(verbose_name='остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
            ],
        ),
    ]
